services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
